### ISSUE TITLE
[Feature]:希望作者大大能再加一个  设置访问密码  功能

### ISSUE THREAD

**Issue by XCQ0607** [raojinlin/notepad-pwa#10]
**添加缘由**
因为我是把这个云笔记当做在任何地方有设备就能查看的网站，所以我想要某些文档需要权限才能访问，这样安全性就能保证。

**解决方案**
1. 最简单的话就是给这整个网页设置访问密码
2. 或者是说如果复杂一点可以设置多用户系统，每个用户管理各自的文章
3. 上面的多用户系统可能工程量要大一点，或者说不加用户体系，管理者仅需一个密码就可以管理文件是否公开。可以设置文章的保护等级，有密码才能修改或访问文件，有些文章是公开的

感谢这个项目给我带来的便利，感谢作者！期待听到回复！

**Comment by raojinlin** [comment]
@XCQ0607 哈哈，可以啊。你提供的解决方案不错，我加一个分享功能吧，可以设置密码访问。

**Comment by raojinlin** [comment]
@XCQ0607 加了用户体系，可以分享笔记、设置访问密码。可以体验一下。

地址：https://notepad-git-feature-note-share-raojinlins-projects.vercel.app/
用户名：demo@notepad-pwa.io
密码：demo123

![image](https://github.com/raojinlin/notepad-pwa/assets/19492031/222d0165-9f49-473d-a45d-f89e05a50873)

**Comment by XCQ0607** [comment]
测试环境:
目前条件有限，测试平台是移动端

测试项目:
1.登陆功能正常✔
![Screenshot_20240426_130601_cn mujiankeji mbrowser](https://github.com/raojinlin/notepad-pwa/assets/125746521/af142251-3292-4100-91d6-27b494ef8781)

2.文件分享正常✔
测试地址:https://notepad-git-feature-note-share-raojinlins-projects.vercel.app/s/K8TWKwIvrby?password=wzWAD
![Screenshot_20240426_130811_cn mujiankeji mbrowser](https://github.com/raojinlin/notepad-pwa/assets/125746521/2dfa688b-ac9f-4287-abb1-e0c3c956270a)

测试视频:

https://github.com/raojinlin/notepad-pwa/assets/125746521/b926ef35-1d62-4db6-a07a-3bacd3f1f7c9



体验总结:
这次更新的功能没有功能异常，且辛苦作者大大完成的更新（ '▿ ' ）

用后建议:
1.多平台适配
符合日常使用笔记的场景是移动端设备。经体验，手机端的某些地方存在显示不全的现象。
如这次更新的文档分享功能，移动端没有显示相关功能的区域。
还有是文档删除功能与重命名在移动端也无法实现。
希望作者大大可以对移动端的界面进行适配。
2.云文档删除机制
我发现在<云笔记>中只有下载的选项，没有删除的选项。当我想要删除一个文档时，在没有点开<自动上传> 时点击的删除按钮，相应的<云笔记>中的对应的被删除的本地文档不会被删除，只是本地的文档被删除了。
可以通过在云云笔记后添加删除选项或在用户点击删除后，询问用户是否同步到云端的方式来解决

感谢作者•ᴗ•

**Comment by raojinlin** [comment]
好的，我继续优化下

**Comment by XCQ0607** [comment]
作者大大，我原本想部署一下这个feature-note-share时。刚开始它报错说我没有填写POSTGRES_URL env，然后我认为可能是新版本需要数据库的支持，所以我就配置了这个环境变量，使用的是vercel的postgres数据库。然后当我再次部署时，又遇到了报错

Error occurred prerendering page "/api/hello". Read more: https://nextjs.org/docs/messages/prerender-error
22:58:36.220 | error: relation "users" does not exist
22:58:36.220 | at /vercel/path0/.next/server/chunks/8.js:4136:25
22:58:36.220 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
22:58:36.220 | at async VercelPgPreparedQuery.execute (/vercel/path0/.next/server/chunks/8.js:14746:27)
22:58:36.220 | at async getExampleTable (/vercel/path0/.next/server/chunks/90.js:112:26)
22:58:36.220 | at async GET (/vercel/path0/.next/server/app/api/hello/route.js:148:5)
22:58:36.220 | at async AppRouteRouteHandler.execute (/vercel/path0/node_modules/next/dist/server/future/route-handlers/app-route-route-handler.js:330:26)
22:58:36.220 | at async AppRouteRouteHandler.handle (/vercel/path0/node_modules/next/dist/server/future/route-handlers/app-route-route-handler.js:410:30)
22:58:36.220 | at async /vercel/path0/node_modules/next/dist/export/worker.js:236:42
22:58:36.220 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
22:58:36.220 | info  - Generating static pages (3/13)
22:58:36.224 | info  - Generating static pages (6/13)
22:58:36.230 | info  - Generating static pages (9/13)
22:58:36.234 | Failed to verify session:  Invalid Compact JWS
22:58:36.546 | info  - Generating static pages (13/13)
22:58:36.548 |  
22:58:36.549 | > Build error occurred
22:58:36.551 | Error: Export encountered errors on following paths:
22:58:36.551 | /api/hello/route: /api/hello
22:58:36.551 | at /vercel/path0/node_modules/next/dist/export/index.js:425:19
22:58:36.551 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
22:58:36.551 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
22:58:36.551 | at async /vercel/path0/node_modules/next/dist/build/index.js:1422:21
22:58:36.551 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
22:58:36.551 | at async /vercel/path0/node_modules/next/dist/build/index.js:1280:17
22:58:36.555 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
22:58:36.555 | at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:73:29)
22:58:36.620 | Error: Command "npm run build" exited with 1


环境变量填的是"postgres://default:************@ep-summer-block-a1719897.ap-southeast-1.aws.neon.tech:5432/verceldb?sslmode=require"
看到三天前更新了新的预览版本，我就想自己部署试试，可能是我太急了吧。
我只是想问一下是哪里出了问题，我其实是个半路小白，只能瞻仰大佬的项目，我能力有限了
应该是功能还在改善，所以还没有更新readme

![image](https://github.com/raojinlin/notepad-pwa/assets/125746521/29c63035-7090-4e91-8a0f-532f6afe2dec)


看到正在开发了，慢慢开发，不急的，辛苦了作者大大！！

**Comment by raojinlin** [comment]
这个分支新增了数据库，文档还没有补上。配置了POSTGRES_URL_ENV之后，需要把表结构迁移过去。运行下下面的命令进行迁移：
```bash
npm run migrations:migrate 
```

移动版适配还在进行中，有兴趣的话可以加入^-^

**Comment by raojinlin** [comment]
移动端适配工作量太大，后面有时间在上了

**Comment by XCQ0607** [comment]
主要是我现在还是一名高中生，目前代码层面还没有涉及，只涉及了一些表层知识，没有应用的经验。但是我对这方面很有兴趣，将来我有能力了一定会贡献这个仓库的。感谢作者的贡献！！

**Comment by XCQ0607** [comment]
我刚刚装好测试了一下，把我的笔记转进去了。
但是我有一个疑问，npm run migrations:migrate ,这个命令是必要的吗？
使用web端vercel部署的话，这个命令怎么执行啊？
我没有执行这个命令，但是数据库表自动生成了
![image](https://github.com/raojinlin/notepad-pwa/assets/125746521/b03ac29d-62f8-4471-9676-5c077111e2f7)
设置好了env，vercel也部署成功了，web也显示页面了，也可以注册用户了，登录写文章自动保存，时间右边也有小勾号表示上传成功
![image](https://github.com/raojinlin/notepad-pwa/assets/125746521/5f144c29-45fc-43ae-8739-7d49c4579919)
但是问题是当我清除cookie再次登录时，却变成了这样
![image](https://github.com/raojinlin/notepad-pwa/assets/125746521/5a8b4ced-6e22-4165-bd34-060134dd56fd)
无法下载笔记
而且点击云笔记，直接退出登录
因此我再去查看数据库内内容
只有nt_sessions表与users表有内容
![image](https://github.com/raojinlin/notepad-pwa/assets/125746521/d4523778-9d88-419f-8b6e-be92cf2df703)
这是为什么啊？
